#define MSG_UNAVAILABLE "Routine Temporaily Unavailable"
#define CLIENT_CLASS    "SYSINFO Class"
#define TITLE           "Sysinfo - (C)opyright, 1992 - Gene Backlin"
#define HELPTITLE       "Sysinfo Help Window"
#define HELPFILE        "SYSINFO.HLP"

#define ID_RESOURCE                    100
#define ID_MENU_RESOURCE               110
#define ID_NOTEBOOK                    120

#define IDM_DISPLAY                    1000
#define IDM_DIS_NOTEBOOK               1001
#define IDM_DIS_NOTEBOOK_EXIT          1099

#define IDM_EXIT                       1800

#define IDM_HELP                       1900
#define IDM_HEL_SEP1                   1901
#define IDM_HEL_SEP2                   1902
#define IDM_HEL_ABOUT                  1910
#define IDM_HELP_FOR_HELP              1911
#define IDM_MENU_EXTENDED_HELP         1912
#define IDM_EXTENDED_HELP              ID_MENU_RESOURCE
#define IDM_HELP_FOR_SYSINFO           1913

#define MAIN_HELPTABLE                 2000
#define SUBTABLE_OPTION                2001

#define IDM_HELP_DISPLAY               IDM_DISPLAY
#define IDM_HELP_NOTEBOOK              IDM_DIS_NOTEBOOK
#define IDM_HELP_EXIT                  IDM_EXIT
#define IDM_HELP_HELP                  IDM_HELP
#define IDM_HELP_MENU_EXTENDED_HELP    IDM_MENU_EXTENDED_HELP
#define IDM_HELP_HELP_FOR_HELP         IDM_HELP_FOR_HELP

#define IDD_DIS_INFO_DLG            2100
#define IDD_DIS_MAX_PATH_FLD        2101
#define IDD_DIS_MAX_TEXT_FLD        2103
#define IDD_DIS_MAX_PMSESS_FLD      2105
#define IDD_DIS_MAX_VDMSESS_FLD     2107
#define IDD_DIS_BOOTDRIVE_FLD       2109
#define IDD_DIS_DYNPRI_FLD          2112
#define IDD_DIS_MAX_WAIT_FLD        2114
#define IDD_DIS_MIN_TIMESLICE_FLD   2116
#define IDD_DIS_MAX_TIMESLICE_FLD   2118
#define IDD_DIS_PAGESIZE_FLD        2120
#define IDD_DIS_MAX_COMP_LEN_FLD    2124
#define IDD_DIS_MS_COUNTER_FLD      2126
#define IDD_DIS_LO_TIME_FLD         2128
#define IDD_DIS_HI_TIME_FLD         2130
#define IDD_DIS_TOT_PHY_MEM_FLD     2132
#define IDD_DIS_TOT_RES_MEM_FLD     2134
#define IDD_DIS_TOT_AVAIL_MEM_FLD   2136
#define IDD_DIS_MAX_PRIVATE_MEM_FLD 2138
#define IDD_DIS_MAX_SHARED_MEM_FLD  2140
#define IDD_DIS_TIME_INTERVAL_FLD   2142

#define IDD_NB_NOTEBOOK_CLOSE       2198
#define IDD_DIS_HELP                2199

#define IDD_ABOUTBOX                   3000

#define IDD_NB_PAGE1                5010
#define IDD_NB_PAGE1A               5011
#define IDD_NB_PAGE1B               5012
#define IDD_NB_PAGE2                5020
#define IDD_NB_PAGE2A               5021
#define IDD_NB_PAGE3                5030
#define IDD_NB_PAGE3A               5031
#define IDD_NB_PAGE_HELP            5998
#define IDD_NB_EXIT_PAGE            5999
#define IDD_VERSION                 5013
